name: this is a test workflow
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: write-script
        run: echo "hellow this is the first world"
      - name: install npm
        run: npm install
      - name: install composer
        run: composer install
      - name: migrate app
        run: php artisan migrate

